### PR TITLE
Update contact.dart

### PR DESCRIPTION
**Pull request by worldbucks**
Check for Contact Date NULL otherwise it will throw an exception data != null

### CODE REVIEW

**Comment by kw2019ltd** [comment]
pls merge this pr

**Comment by SamiKouatli** [comment]
This PR does fix the « exception data != null » that happens on some devices. This needs to be merged.

**Comment by greebie** [comment]
Tested approach after experiencing issue #7 on LM G710 and it worked. Please merge.

**Comment by ericmartineau** [comment]
Thanks for this PR

**Pull request merged**
